### Load and Visualize the Tree.

# **Hypothesis:** The resulting tree will show a "star-like" topology for the Omicron clade, with low
# bootstrap support on the short internal branches, providing visual evidence of adaptive radiation.

# --- New Cell ---

# Install ete3 for phylogenetic tree visualization
print("Installing ete3...")
!pip install -q ete3

from ete3 import Tree

# 2. Define the input file generated by the bootstrap run
# This file contains the tree with bootstrap support values on the nodes.
TREE_FILE_WITH_SUPPORT = "sequence_aligned.fas.contree"

# 3. Load and print the tree structure
try:
    # format=1 for ete3 to look for support values on internal nodes
    t = Tree(TREE_FILE_WITH_SUPPORT, format=1)

    print("\n--- Phylogenetic Tree with Bootstrap Support ---")
    print("Bootstrap values are shown in brackets on the internal nodes.\n")

    # ASCII representation of the tree to visualize it directly
    # The 'show_internal=True' flag is important to see the node names and support
    tree_ascii = t.get_ascii(show_internal=True)
    print(tree_ascii)

except FileNotFoundError:
    print(f"ERROR: The tree file '{TREE_FILE_WITH_SUPPORT}' was not found.")
except Exception as e:
    print(f"An error occurred while parsing the tree: {e}")