# -*- coding: utf-8 -*-
"""
#### Processing a SARS-CoV-2 Mutation Dataset across a Phylogenetic Tree

This Colab Notebook shows a procedure to extract the set of parsimony-inferred mutations from branches of a phylogenetic tree as generated by the UShER toolkit (.pb formatted file). It is dependent on matUtils for file handling.

Assumptions: installation of the UShER toolkit which includes matUtils and an active internet connection to download the MAT file. This notebook is designed for Google Colab but may be modified for other systems. The current configuration is to copy the output file to Google MyDrive, but this may be changed to one of its subdirectories instead.

##### 1. Mount Google MyDrive in Google Colab
"""

from google.colab import drive
import os

# Mount drive for file management
# For Google Colab: had to activate all allowable permissions for access to MyDrive to avoid authentication error
drive.mount('/content/drive')
os.chdir('/content/drive/MyDrive')

"""##### 2. Installation of Conda for Google Colab"""

# Create subdirectory named usher
# !mkdir -p usher

# Install condacolab
!pip install -q condacolab
# Install Conda
import condacolab; condacolab.install()
# Initialize the shell and restart the kernel
# Google Colab usually restarts by itself and reports a warning message
#  however, the installation procedure is expected to continue
!conda init bash
# Verify installation
!conda --version

"""##### 3. Installation of the UShER toolkit via Conda"""

# The following are Bash shell commands
# Installation of UShER for Conda (local build), otherwise see documentation for other options:
#  https://usher-wiki.readthedocs.io/en/latest/Installation.html
# Create a new environment for UShER
!conda create -n usher-env # python=3.10 # to support BTE library, if installed
# Activate the newly created environment
!conda activate usher-env

# Set up channels
!conda config --add channels defaults
!conda config --add channels bioconda
!conda config --add channels conda-forge
# Install the UShER package
!conda install -q usher

"""##### 4. Download the UShER Mutation-Annotated Tree (MAT) data"""

# The following are Bash shell commands
# Verify the output files (usher_tree.nwk, mutations.tsv) are created

# Download the latest MAT file:
! wget http://hgdownload.soe.ucsc.edu/goldenPath/wuhCor1/UShER_SARS-CoV-2/public-latest.all.masked.pb.gz

# Uncompress file (the -f parameter will cause an overwrite if the file is already present in the directory)
# Creates public-latest.all.masked.pb
!gunzip -f public-latest.all.masked.pb.gz

# Export a Newick tree (using the decompressed .pb file)
# May activate this line if the Newick tree is required for downstream processing
# !matUtils extract --input-mat public-latest.all.masked.pb --write-tree usher_tree.nwk

# Export a summary of node statistics for the input .pb file
# !matUtils summary --input-mat public-latest.all.masked.pb --node-stats node_stats.tsv

# Export other summary data (UShER's parsimony algorithm) associated with its phylogenetic tree
# !matUtils summary --get-all-basic --input-mat public-latest.all.masked.pb
# !matUtils summary --input-mat public-latest.all.masked.pb --mutations mutations.tsv

# Optional: copy output files at Google Colab to Google MyDrive
#  may also add bash shell code to use a subdirectory of MyDrive instead
# !cp usher_tree.nwk /content/drive/MyDrive
# !cp node_stats.tsv /content/drive/MyDrive
# !cp mutations.tsv /content/drive/MyDrive
