# -*- coding: utf-8 -*-
#### Analyzing SARS-CoV-2 Branch Mutations with UShER and Python

This Jupyter Notebook is for a procedure to extract and associate a set of parsimony-inferred mutations with branches of a phylogenetic tree as generated by the UShER toolkit. It is dependent on matUtils for the dataset and Python with dendropy and pandas to process it.

Assumptions: installation of the UShER toolkit which includes matUtils and an active internet connection to download the MAT file from the UCSC Genome Browser. This notebook is designed for Google Colab but may be modified for other systems.

##### 1. Mount Google MyDrive in Google Colab
"""

from google.colab import drive
import os

# mount drive for file management
# for Google Colab, may have to accept all permissions for accessing MyDrive if an authentication error occurs
drive.mount('/content/drive')
os.chdir('/content/drive/MyDrive')

"""##### 2. Installation of Conda for Google Colab"""

# create a directory named usher
!mkdir -p usher

# Install condacolab
!pip install -q condacolab
# Install Conda
import condacolab; condacolab.install()
# Initialize the shell and restart the kernel
!conda init bash
# Verify installation
!conda --version

"""##### 3. Installation of the UShER toolkit via Conda"""

# Installation of UShER for Conda (local build), otherwise see documentation for other options:
#  https://usher-wiki.readthedocs.io/en/latest/Installation.html
# Create a new environment for UShER
!conda create -n usher-env
# Activate the newly created environment
!conda activate usher-env
# Set up channels
!conda config --add channels defaults
!conda config --add channels bioconda
!conda config --add channels conda-forge
# Install the UShER package
!conda -q install usher

"""##### 4. Preparing Input Files with matUtils

Download the UShER Mutation-Annotated Tree (MAT) and next extract the Newick tree and branch mutations using the matUtils commandline tool.
"""

# The following are Bash shell commands that should be run before the Python code.
# Verify the necessary files (usher_tree.nwk, usher_branch_mutations.tsv) are present.

# Download the latest MAT file (if not already done):
! wget http://hgdownload.soe.ucsc.edu/goldenPath/wuhCor1/UShER_SARS-CoV-2/public-latest.all.masked.pb.gz

# Uncompress file (the -f parameter will cause an overwrite if the file is already present in the directory)
# Creates public-latest.all.masked.pb
!gunzip -f public-latest.all.masked.pb.gz

# Export the Newick tree (using the decompressed .pb file)
!matUtils extract --input-mat public-latest.all.masked.pb --write-tree usher_tree.nwk

# Export a list of all mutations (UShER's parsimony algorithm) associated with each branch (node) in the tree
!matUtils summary --get-all-basic --input-mat public-latest.all.masked.pb

"""#### 5. Python Script: Associating Mutations with Tree Branches

Next, read the usher_tree.nwk and usher_branch_mutations.tsv files, and then programmatically associate the mutations with the corresponding nodes (representing the end of a branch from its parent).

##### 5.1. Install Required Libraries
"""

# Uncomment the following lines and run if these libraries are not installed
# Google Colab has the pandas library by default
# !pip install pandas
!pip install dendropy

import dendropy
import pandas as pd
from collections import defaultdict

"""##### 5.2. Load the Tree and Mutation Data

This cell will load a Newick tree into a dendropy object and branch mutations into a pandas DataFrame, which is next then converted into a dictionary for accessing by a lookup.
"""

# Define input file names
tree_file = "usher_tree.nwk"
mutations_file = "mutations.tsv"

print(f"Loading tree from: {tree_file}")
tree = dendropy.Tree.get_from_path(tree_file, schema="newick", preserve_underscores=True)
# UShER trees are usually rooted, but if yours is unrooted, you might need to root it:
tree.reroot_at_midpoint(update_bipartitions=False)
print(f"Tree loaded with {len(tree.nodes())} nodes and {len(tree.leaf_nodes())} leaf nodes.")

print(f"Loading mutations from: {mutations_file}")
# Assumes the TSV has two columns: Node_ID and Mutations (comma-separated string)
# Adjust 'sep' if your file is comma-separated or uses a different delimiter.
try:
    mutations_df = pd.read_csv(mutations_file, sep='\t', header=None, names=['Node_ID', 'Mutations'], engine='python')
except pd.errors.EmptyDataError:
    print(f"Warning: {mutations_file} is empty or not formatted as expected. Proceeding with an empty mutation map.")
    mutations_df = pd.DataFrame(columns=['Node_ID', 'Mutations'])
except FileNotFoundError:
    print(f"Error: The mutations file '{mutations_file}' was not found. Please ensure it exists in the correct path.")
    exit()


# Convert the DataFrame to a dictionary for faster lookup
# Node_ID will be the key, and a list of mutation strings will be the value
node_to_mutations = defaultdict(list)
for index, row in mutations_df.iterrows():
    node_id = str(row['Node_ID']) # Ensure ID is string for consistent lookup
    mutations_str = row['Mutations']
    if pd.notna(mutations_str) and str(mutations_str).strip(): # Check for NaN or empty/whitespace-only strings
        node_to_mutations[node_id] = [m.strip() for m in str(mutations_str).split(',')]

print(f"Loaded mutations for {len(node_to_mutations)} nodes/branches.")

"""##### 5.3. Traverse the Tree and Associate Mutations

This section will iterate through every node in the phylogenetic tree. For each node, it will attempt to find the mutations associated with the branch leading to that node (from its parent) in the node_to_mutations dictionary. It will then store these mutations directly as annotations on the dendropy node object.

Important Note on Node Identifiers:
UShER's matUtils summary output of mutations typically uses the taxon label for leaf nodes (assigned sample names) and often generates internal node IDs that might be different from dendropy's default internal node object IDs (oid). For a robust solution, it is ideal to have consistent mapping.

A common strategy is to use the Node_ID directly from the mutations.txt file as the identifier and assign dendropy's node.taxon.label for leaves and node.annotations.get_value('user_id') or node.oid for internal nodes to the Node_ID from the tab-delimited text file. For UShER, internal nodes in the mutations.txt output are often represented by the Node_ID of their closest descendant leaf or a generated unique ID. In this case, the Node_ID is from the above tab-delimited file.

"""

# Dictionary to store mutations mapped by the node_id from the tab-delimited text file
final_branch_mutations_map = {}

# Iterate through all nodes in the tree
for node in tree.postorder_node_iter():
    # The Node_ID in usher_branch_mutations.tsv is the label of the node where the branch *ends*.
    # For leaf nodes, this is usually the sample name (taxon.label).
    # For internal nodes, UShER might assign unique IDs, or they might be unlabeled in the Newick.
    # This script uses node.taxon.label for leaves and node.label for internal nodes if available.
    # If internal nodes in your Newick are unlabeled, node.oid (Dendropy's internal object ID) can be used,
    # but mapping this to UShER's dump output might require more sophisticated matching if UShER's
    # internal node IDs in the dump file are not simple OIDs.

    current_node_id_str = None
    if node.is_leaf() and node.taxon:
        current_node_id_str = str(node.taxon.label)
    elif node.label: # Check if an internal node has an explicit label in the Newick
        current_node_id_str = str(node.label)
    else: # Fallback for unlabeled internal nodes (less reliable for matching dump output)
        current_node_id_str = str(node.oid)


    mutations_on_this_branch = node_to_mutations.get(current_node_id_str, [])
    node.annotations.add_new('branch_mutations', mutations_on_this_branch)
    final_branch_mutations_map[current_node_id_str] = mutations_on_this_branch

print("Mutations associated with tree nodes.")

"""##### 5.4. Visualize or Output Results

Next, choose to print the results, save them to a new file, use dendropy's visualization capabilities, or export the tree with annotations for use in other phylogenetic viewers.

##### 6. Further Analysis for Output Results
"""

output_file_name = "annotated_branch_mutations.txt"
print(f"\nWriting branch mutations to {output_file_name}...")

with open(output_file_name, "w") as f:
    for node_id, mutations in final_branch_mutations_map.items():
        if mutations: # Only write branches that actually have mutations
            f.write(f"Branch leading to Node: {node_id}\n")
            for mut in mutations:
                f.write(f"  - {mut}\n")
            f.write("\n")

print("Finished writing results.")

"""#### (Optional) 7. Additional Dendropy based processing."""

print("\n--- Example of annotated nodes (first 5 with mutations) ---")
count = 0
for node in tree.postorder_node_iter(): # Iterate again to show annotations
    node_muts = node.annotations.get_value('branch_mutations')
    if node_muts:
        node_display_id = node.taxon.label if node.taxon else node.label if node.label else node.oid
        print(f"Node Label (or OID): {node_display_id}")
        print(f"  Mutations: {node_muts}")
        count += 1
    if count >= 5:
        break

# Example: for exporting the tree with annotations
# (see Dendropy documentation for specific format support like NeXML)
# annotated_tree_file = "usher_tree_with_annotations.nex"
# try:
#   tree.write(path=annotated_tree_file, schema="nexus", suppress_annotations=False, unquoted_underscores=True)
#   print(f"Annotated tree saved to {annotated_tree_file}")
# except Exception as e:
#   print(f"Could not save annotated tree as NEXUS: {e}")
#   print("Consider 'newick' schema if NEXUS fails, though Newick doesn't typically support rich annotations.")
